theme: jekyll-theme-hacker
title: root@codex #
description: Welcome to my terminal window! I randomly post stuff here when I get get bored (a lot) and/or make evil things (usually not very pog) >:D. I\'ll also be posting any future CTF challenges I find fun. Might try to dig up old CTF solutions, if im bored enough.
